// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/twpayne/go-geom"
)

type City struct {
	ID   int64      `json:"id"`
	Name string     `json:"name"`
	Geom geom.Point `json:"geom"`
}

type Edge struct {
	ID         int64   `json:"id"`
	FromNodeID int64   `json:"from_node_id"`
	ToNodeID   int64   `json:"to_node_id"`
	Weight     float64 `json:"weight"`
}

type Node struct {
	ID   int64      `json:"id"`
	Name string     `json:"name"`
	Geom geom.Point `json:"geom"`
}
